#!/usr/bin/python

import datetime
import sys

def datetime_to_unix(inp):
    if(len(inp.split(' ')) == 2):
        try:
            d = datetime.datetime.strptime(inp,"%Y-%m-%d %H:%M:%S")
        except Exception as e:
            print e
            return

    if(len(inp.split(' ')) == 1):
        try:
            d = datetime.datetime.strptime(inp,"%Y-%m-%d")
        except Exception as e:
            print e
            return

    print d.strftime("%s")

    
if __name__ == '__main__':
    datetime_to_unix(sys.argv[1])
