#!/bin/sh

# checks if a program is running, if not, it tries to start it.
# after 3 tries, if the program hasn't started we print out the error
# and return.

errors=""
check_prog ()
{
    if [ $count -eq 3 ]
    then 
	printf "\t *** issue starting:'$1',\t '$errors' \n"
	return
    else
	count=$(expr $count + 1)
    fi
    if [ $(pgrep -x "$1") ]
    then 
	printf "\t * %-20s (running: %10s\n" "$1" "pid: $(pgrep -x "$1"))"
    else
	if [ $count -eq 1 ]
	then
	    printf "\t * $1 not running, starting up\n"
	fi
	errors=$($1 2>&1)

	check_prog $1
    fi
}

count=0
check_prog mpd
count=0
check_prog mpdscribble
