#!/usr/bin/python
import datetime
import sys

def unix_to_datetime(inp):
    print(datetime.datetime.fromtimestamp(int(inp)).strftime('%Y-%m-%d %H:%M:%S'))


if __name__ == '__main__':
    unix_to_datetime(int(sys.argv[1]))

